### ISSUE TITLE
Building issue with SDK 4.2

### ISSUE THREAD

**Issue by BartDewancker** [AxisCommunications/acap-native-sdk#23]
Hi support team,

I'm trying to build a small application (see test_vdostream.zip) with SDK 4.2 for artpec-8. This application calls some functions from the vdostream library. The procedure how I try to build the application is described in the document 'Building an ACAP application with SDK 4_2'. As you can see there is a linking problem with glib-2.0 (version 2.66.7) and glibc 2.33. Do you have any idea what is causing this error? I also noted the container environment settings in the document. Maybe this can help.

I have the same issue with SDK 3.5. However, building the application with SDK 3.1 on a non-containerized Linux platform (glib-2.0 version 2.60.7 and glibc 2.30) works fine and runs on an artpec-8 camera.

Thanks in advance
Bart Dewancker
Araani

[test_vdostream.zip](https://github.com/AxisCommunications/acap-native-sdk/files/8956408/test_vdostream.zip)

![acapsdk4 2](https://user-images.githubusercontent.com/103241379/174997593-a8438863-e6f4-4900-869a-a06fd08023f3.PNG)

[Building ACAP application with SDK 4_2.docx](https://github.com/AxisCommunications/acap-native-sdk/files/8956391/Building.ACAP.application.with.SDK.4_2.docx)

[Dockerfile.docx](https://github.com/AxisCommunications/acap-native-sdk/files/8956392/Dockerfile.docx)

**Comment by BartDewancker** [comment]
I did some more build testing and found that building our ACAP works in a containerized environment with ACAP SDK3.3. This version uses libc 2.31. With SDK 3.4, the build fails. I see in the documentation that for SDK 3.4, libc 2.32 is implemented. As of this version, could there be a mismatch between glib-2.0 and libc?

**Comment by pataxis** [comment]
Hi,

Since you have an application built with pre-containerized ACAP SDK, i.e. version < 3.2 that you try to move to a containerized version, I will give you pointers referring to ACAP SDK 3.5. I would recommend to get the build to work for this version before trying to move to ACAP 4.

## You don't need to rebuild the SDK to install additional build tools like cmake

I have written a general answer [here](https://github.com/AxisCommunications/acap-native-sdk-examples/discussions/58) on our GitHub Discussions.

## SDK and libc version

The compatibility of an SDK is discussed in ACAP 3 SDK [documentation](https://help.axis.com/acap-3-developer-guide#compatibility) and in ACAP 4 SDK [documentation](https://axiscommunications.github.io/acap-documentation/docs/axis-devices.html).

When you build an application with an SDK version according to our [ACAP application examples](https://github.com/AxisCommunications/acap3-examples), you will build and link the application with a certain libc version that is also found in the corresponding AXIS OS version. Any API libraries in the SDK that you link to in your application have been built with the same libc version.

Since libc is backwards compatible, it means that building the application with a libc version and linking to API libraries compiled with the same libc version, your application will be possible to install on the specified AXIS OS version or later.

Building an application with ACAP SDK 3.5 (glibc 2.33) will make it [compatible](https://help.axis.com/acap-3-developer-guide#find-the-right-sdk-for-software-compatibility) with AXIS OS 10.9 or later.

The ACAP application build procedure is using `make` underneath and some things are assumed here to build with the correct libc version.

1. Source the build environment file `/opt/axis/acapsdk/environment-setup*` to set build environment variables like `CC` used in `Makefile`. The variables are set up to point to the SDK path which contains the correct libc version.
    ```Dockerfile
   RUN . /opt/axis/acapsdk/environment-setup* && \
    acap-build .
    ```
   If you have a package.conf application and no manifest.json, replace `acap-build .`, see the [documentation](https://help.axis.com/acap-3-developer-guide#package-configuration-file) for more info. 
2. In Makefile, if you are linking to API libraries in the SDK path, use `pkg-config` to expand dependencies. See for example the [vdostream](https://github.com/AxisCommunications/acap3-examples/blob/master/vdostream/app/Makefile) example.
    ```Makefile
   CFLAGS += $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --cflags $(PKGS))
   LDLIBS += $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --libs $(PKGS))
    ```
3. The build step in the `Makefile` use the environment variables with correct SDK paths
    ```Makefile
   $(CC) $(CFLAGS) $(LDFLAGS) $^ $(LDLIBS) -o $@
    ```

### Wrong libc version and errors

We have seen errors simliar to `undefined reference to 'stat64@GLIBC_2.33'` in tests and development. They have occurred when linking to an API library in the SDK which is compiled with a **newer libc version** like 2.33 but GCC is wrongly using the libc of the Ubuntu container image which is an **older libc version** like 2.31 and therefore can't find the newer 2.33 symbols/functions.

Not following the steps outlined above could lead to this. Here are some possible pitfalls:

- Not sourcing the SDK environment
- Not expanding the API dependencies with `pkg-config`
- Building libraries with a **newer libc version** on a build machine and then copy them in to the ACAP SDK container image which has an **older libc version**. See the examples for [utility-libraries](https://github.com/AxisCommunications/acap3-examples/tree/master/utility-libraries) for how libraries can be built inside the SDK environment instead.

## Other build tools than make

Building the ACAP application with other tools than `make` and `Makefile` is not something we support today.

## Move from ACAP3 to ACAP4

If you have got it to work in ACAP SDK 3.5, you could go on and check this [page](https://axiscommunications.github.io/acap-documentation/docs/introduction/acap4-vs-acap3.html) that discuss the differences between ACAP 3 and ACAP 4 which hopefully can give you information of what would be required for your application.

**Comment by BartDewancker** [comment]
Thank you for your detailed answer. We finally managed to build our ACAP with SDK 3.5 and SDK 4.2. The problem was indeed that the cross compiler used the host libc instead of the target libc. An incorrect notation of the compiler arguments in the toolchain file was the cause of the problem.

Regards
Bart

**Comment by BartDewancker** [comment]
Hi Patrik,

Thank you for your detailed answer. We finally managed to build our ACAP with SDK 3.5 and SDK 4.2. The problem was indeed that the cross compiler used the host libc instead of the target libc. An incorrect notation of the compiler arguments in the toolchain file was the cause of the problem.

I closed the issue in github.

Regards
Bart
